[package]
name = "async-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["sync"] }
serde = { version = "1.0.215", features = ["derive", "rc"] }
async-std = { version = "1.13.0", features = ["unstable"] }
serde_json = "1.0"
